theme: jekyll-theme-cayman
title: gSwitch
show_downloads: "true"
github:
  zip_url: "https://github.com/CodySchrank/gSwitch/releases/download/1.8.0/gSwitch.zip"
  issue_url: "https://github.com/CodySchrank/gSwitch/issues"
